services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - lan
    ports:
      - "127.0.0.1:8080:80"

  siege:
    build:
      context: ./siege
    network_mode: host
    

networks:
  lan:
    driver: bridge