FROM nginx:stable-alpine3.20

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/html/web

COPY ./web /usr/share/nginx/html/web

EXPOSE 80/tcp

ENTRYPOINT [ "nginx" ]

CMD [ "-g", "daemon off;" ]